on:
  push:
    branches:
      - master
      - main

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      ttl: ${{ steps.set-matrix.outputs.ttl }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            *.ttl
      
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - id: set-matrix
        run: echo "ttl=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT


  validate:
    runs-on: ubuntu-latest
    needs: changedfiles
    # only run there are changed files
    # if: ${{needs.changedfiles.outputs.ttl}}
    strategy:
      matrix:
        ttl-file: ${{ needs.changedfiles.outputs.ttl }}
    steps:
      - name: echo changed files
        run: echo "${{ matrix.ttl-file }}"
