on:
  push:
    branches:
      - master
      - main

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      ttl: ${{ steps.set-matrix.outputs.ttl }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            *.ttl
          json: "true"

      - name: Set matrix
        id: set-matrix
        run: echo "ttl=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

  validate:
    runs-on: ubuntu-latest
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.ttl}}
    strategy:
      fail-fast: false # other validation jobs should continue checking even if one file is invalid
      matrix:
        file: ${{ fromJson(needs.changedfiles.outputs.ttl) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # OR "2" -> To retrieve the preceding commit.
      - name: echo changed files
        run: echo "${{ matrix.file }}"

      - name: Validate with script
        run: bash ${GITHUB_WORKSPACE}/scripts/validate-skos.sh -f ${GITHUB_WORKSPACE}/${{ matrix.file }} -s ${GITHUB_WORKSPACE}/scripts/skos.shacl.ttl
